### ISSUE TITLE
Samples force you to enter a password

### ISSUE THREAD

**Issue by aaron-613** [SolaceSamples/solace-samples-java#54]
All of the basic samples force a password to be passed in on the command line.  This is not ideal when first connecting to the Software broker that has the `default` VPN and `default` client-username enabled, and no password is required.

I'm happy to do the fix myself, to get practice with GitHub's contributing methods.

Note: this doesn't apply to the _features_ ones, which look to be taken from the API's original examples.

**Comment by mdspielman** [comment]
Using a password is a best practice. So that is why we've created the samples this way. 

It also works with the default setup of the PSB and messaging services from PubSub+ Cloud which require a password by default. So this is design intent currently in the samples.

We could update the readme to suggest a user of something like "demo" with password "demo" for the standard PSB if you thought that would clarify the expected usage.

**Comment by aaron-613** [comment]
> Using a password is a best practice.
Agreed!  But it's also non-intuitive to have to enter a junk one when not required.

> It also works with the default setup of the PSB...
PSB = software broker?  Doesn't require a password by default.

Having optional password also harmonizes with the _feature_ samples, SdkPerf, as well the actual API.

I've already done the code change, and am about to do a pull request.  Take a look, and if you don't like it, you can reject.  It's still pretty clear that a password is expected, but optional.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. :sleeping:
To have this issue re-opened please add a comment below with a detailed explanation.  
Thank you for your contributions :heart:
