### ISSUE TITLE
Error running gradlew in cygwin due to carriage return

### ISSUE THREAD

**Issue by ghaithdallaali** [SolaceSamples/solace-samples-java#7]
Error in question:

```
$ ./gradlew assemble
./gradlew: line 2: $'\r': command not found
./gradlew: line 8: $'\r': command not found
./gradlew: line 36: syntax error near unexpected token `$'{\r''
'/gradlew: line 36: `warn ( ) {
```

Can be fixed using unix2dos.exe

**Comment by wari** [comment]
I believe the reason why this happens is due to how git clones for your operating system. See [Dealing with Line Endings](https://help.github.com/articles/dealing-with-line-endings/) for how you can make git for windows checkout with unix line endings.

Note that MingW based bash.exe does not have a problem reading with DOS formatted files, while **Bash on Ubuntu For Windows** and cygwin will fail on a checkout with DOS line endings.

I've checked gradlew in linux and `gradlew` does not have `\r\n` for line endings.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. :sleeping:
To have this issue re-opened please add a comment below with a detailed explanation.  
Thank you for your contributions :heart:
